In [1]:
import torch


In [13]:
x= torch.rand(5,3, dtype=torch.float)
print(x)

tensor([[0.6612, 0.7434, 0.1656],
        [0.6399, 0.6992, 0.0150],
        [0.6593, 0.5604, 0.9749],
        [0.6548, 0.2496, 0.4923],
        [0.6368, 0.4491, 0.2400]])


In [30]:
x= torch.tensor([5,3,2])
x

tensor([5, 3, 2])

In [19]:
x.size()

torch.Size([3])

In [20]:
x=x.new_ones(3,)

In [21]:
x

tensor([1, 1, 1])

In [31]:
x=torch.randn_like(x, dtype=torch.float)

In [32]:
print(x)

tensor([-0.4549, -0.4549, -1.3356])


In [33]:
y =torch.rand(3)

In [34]:
x+y

tensor([ 0.0409, -0.4265, -0.4696])

In [38]:
torch.add(x,y, out=r)

tensor([ 0.0409, -0.4265, -0.4696])

In [37]:
r=torch.empty(3)

In [39]:
r

tensor([ 0.0409, -0.4265, -0.4696])

In [40]:
y.add_(x)

tensor([ 0.0409, -0.4265, -0.4696])

tensor([ 0.0409, -0.4265, -0.4696])


In [42]:
x=torch.rand(5,3)

In [43]:
x

tensor([[0.5429, 0.5057, 0.4378],
        [0.9720, 0.2509, 0.1239],
        [0.3836, 0.0288, 0.0399],
        [0.7209, 0.9485, 0.9573],
        [0.8878, 0.9616, 0.2783]])

In [47]:
x[:,0:3]

tensor([[0.5429, 0.5057, 0.4378],
        [0.9720, 0.2509, 0.1239],
        [0.3836, 0.0288, 0.0399],
        [0.7209, 0.9485, 0.9573],
        [0.8878, 0.9616, 0.2783]])

In [50]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [54]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2177])
0.2177393138408661


In [55]:
a = torch.ones(5)
print(a)


tensor([1., 1., 1., 1., 1.])


In [56]:
a=a.numpy()

In [57]:
a

array([1., 1., 1., 1., 1.], dtype=float32)

In [59]:
a=a.torch()

AttributeError: 'numpy.ndarray' object has no attribute 'torch'

In [60]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [61]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [62]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [63]:
a.add_(3)

tensor([5., 5., 5., 5., 5.])

In [64]:
b

array([5., 5., 5., 5., 5.], dtype=float32)

In [65]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
